# Pandas Library

**Pandas Library:** This is used in **Data Analysis** it works with **tabular data**.It Uses 2 powerful tools they are **DataFrames and Series**.

#Series

### Create Pandas Series in a List

**Series :** Series is a **Data Structure** in Pandas that holds a **numeric array along with a Labeled Index**.

> **Syntax :** pd.series(data , Labeled Index)



In [ ]:
# Load the required Libraries
import numpy as np
import pandas as pd

In [ ]:
# Create an Array
myindex = ['Jungkook','Taehyung','Namjoon']
mydata = [26,28,29]

In [ ]:
# using Series that converts the data to tabular format with default numeric index
myser = pd.Series(data = mydata)
myser

0    26
1    28
2    29
dtype: int64

In [ ]:
# Series with labeled index
myser = pd.Series(data = mydata , index = myindex)
myser

Jungkook    26
Taehyung    28
Namjoon     29
dtype: int64

In [ ]:
# To find the type()
type(myser)

pandas.core.series.Series

In [ ]:
# Series with labeled index without the variables data and index
myser = pd.Series(mydata , myindex)
myser

Jungkook    26
Taehyung    28
Namjoon     29
dtype: int64

### Accessing the Data from Series

In [ ]:
# Access the required element by default index
myser[0]

26

In [ ]:
# Access the required element by labelec index
myser['Jungkook']

26

### Create Pandas Series in Dictionaries

In [ ]:
# Create a Dictionary
ages_of_bts_members = {'Jungkook':26,'Taehyung':28,'Namjoon':29}

In [ ]:
# Display using Series
myser = pd.Series(ages_of_bts_members)
myser

Jungkook    26
Taehyung    28
Namjoon     29
dtype: int64

In [ ]:
# Accessing the values from Series
myser['Jungkook']

26

In [ ]:
# Accessing the values from Series
myser[0]

26

### Operators in Pandas

In [ ]:
# Create a Dictionary
sales_q1 = {'South Korea':100,'India':80,'China':75,'Japan':50}
sales_q2 = {'India':100,'South Korea':90,'Japan':75,'USA':60}

In [ ]:
# Display the series
sales_1 = pd.Series(sales_q1)
sales_1

South Korea    100
India           80
China           75
Japan           50
dtype: int64

In [ ]:
# Display the series
sales_2 = pd.Series(sales_q2)
sales_2

India          100
South Korea     90
Japan           75
USA             60
dtype: int64

In [ ]:
# Normal python multiplication gives
[1,2] * 2

[1, 2, 1, 2]

In [ ]:
# NumPy multiplication gives
np.array([1,2]) * 2

array([2, 4])

In [ ]:
# Multiple the Series 1 with 2
sales_1 * 2

South Korea    200
India          160
China          150
Japan          100
dtype: int64

In [ ]:
# Multiple the Series 2 with 5
sales_2 * 5

India          500
South Korea    450
Japan          375
USA            300
dtype: int64

**keys() :** This is used to access the labeled indices

In [ ]:
# Access the keys using keys()
sales_q1.keys()

dict_keys(['South Korea', 'India', 'China', 'Japan'])

Here we have NaN value while adding the 2 Series in order to remove them use **fill_value = 0 in add()**that displays the original value in the tabulated series





In [ ]:
# Perform addition to the 2 series
sales_1 + sales_2

China            NaN
India          180.0
Japan          125.0
South Korea    190.0
USA              NaN
dtype: float64

**add() :**Does the sum of 2 series

In [ ]:
sales_1.add(sales_2)

China            NaN
India          180.0
Japan          125.0
South Korea    190.0
USA              NaN
dtype: float64

**fill_value = 0 :** Displays the value in the Series to eliminate the NaN

In [ ]:
sum = sales_1.add(sales_2,fill_value = 0)
sum

China           75.0
India          180.0
Japan          125.0
South Korea    190.0
USA             60.0
dtype: float64

In [ ]:
# Datatype to be found for the sum
sum.dtype

dtype('float64')

In [ ]:
# Datatype to be found for a particular series
sales_1.dtype

dtype('int64')

# DataFrame

**DataFrame :** DataFrame is a tabulation with **Rows and Columns** that consist of **same indices** and different columns. **DataFrame is a Group of Series with same index labels.**


> **Syntax :** pd.DataFrame(data , row = index , column = different values)



## Creating a DataFrame in Pandas

In [ ]:
# Create a random DataFrame using NumPy Library
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [ ]:
# Label the Rows as Index
myrow = ['Jungkook','Taehyung','Namjoon','Jimin']
mycol = ['Jan','Feb','Mar']

In [ ]:
# Create DataFrame
df = pd.DataFrame(data = mydata)
df

0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [ ]:
# Now lets add 1 Label that is the common index
df = pd.DataFrame(data = mydata , index = myrow)
df

0   1   2
Jungkook  95  11  81
Taehyung  70  63  87
Namjoon   75   9  77
Jimin     40   4  63

In [ ]:
# Now lets add our Labels
df = pd.DataFrame(mydata,myrow,mycol)
df

Jan  Feb  Mar
Jungkook   95   11   81
Taehyung   70   63   87
Namjoon    75    9   77
Jimin      40    4   63

### Read a CSV File

In [ ]:
# Read a CSV File
df = pd.read_csv('/content/drive/MyDrive/CSV/tips - tips.csv')
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name     CC Number Payment ID  
0    Christy Cunningham  3.560330e+15    Sun2959  
1        Douglas Tucker  4.478070e+15    Sun4608  
2        Travis Walters  6.011812e+15    Sun4458  
3      Nathaniel Harris  4.676138e+15    Sun5260  
4          Tonya Carter  4.832733e+15    Sun2251  
..                  ...           ...        ...  
239       Michael Avila  5.296069e+15    Sat2657  
240      Monica Sanders  3.506806e+15    Sat1766  
241          Keith Wong  6.011892e+15    Sat3880  
242        Dennis Dixon  4.375221e+12      Sat17  
243     Michelle Hardin  3.511452e+15    Thur672  

[244 rows x 11 columns]

### Operations in the CSV files


**columns :**This will read all the **Column indices.**

In [ ]:
# Read the Column Labels
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

**index :**Gives the number of Values from the start to the end with step size

In [ ]:
# Read the number of values in the row
df.index

RangeIndex(start=0, stop=244, step=1)

**head() :**This reads the first 5 values by default from the CSV file

In [ ]:
# Read the first 5 values
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011812e+15    Sun4458  
3    Nathaniel Harris  4.676138e+15    Sun5260  
4        Tonya Carter  4.832733e+15    Sun2251

**tail() :**This reads the last 5 values by default from the CSV file

In [ ]:
# Read the last 10 values
df.tail(10)

total_bill   tip     sex smoker   day    time  size  price_per_person  \
234       15.53  3.00    Male    Yes   Sat  Dinner     2              7.76   
235       10.07  1.25    Male     No   Sat  Dinner     2              5.04   
236       12.60  1.00    Male    Yes   Sat  Dinner     2              6.30   
237       32.83  1.17    Male    Yes   Sat  Dinner     2             16.42   
238       35.83  4.67  Female     No   Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name     CC Number Payment ID  
234    Tracy Douglas  4.097940e+15    Sat7220  
235    Sean Gonzalez  3.534021e+15    Sat4615  
236    Matthew Myers  3.543676e+15    Sat5032  
237     Thomas Brown  4.284723e+15    Sat2929  
238   Kimberly Crane  6.761840e+11    Sat9777  
239    Michael Avila  5.296069e+15    Sat2657  
240   Monica Sanders  3.506806e+15    Sat1766  
241       Keith Wong  6.011892e+15    Sat3880  
242     Dennis Dixon  4.375221e+12      Sat17  
243  Michelle Hardin  3.511452e+15    Thur672

**info() :** This gives the **overall information** about the Data.

In [ ]:
# Get the information of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    float64
 10  Payment ID        244 non-null    object 
dtypes: float64(4), int64(1), object(6)
memory usage: 21.1+ KB


**describe() :** This gives the **Statistical Analysis** of the overall data

In [ ]:
# Statistical analysis
df.describe()

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

**transpose() :** Changes Rows to Columns and Columns to Rows.

In [ ]:
# Statistical analysis
df.describe().transpose()

count          mean           std           min  \
total_bill        244.0  1.978594e+01  8.902412e+00  3.070000e+00   
tip               244.0  2.998279e+00  1.383638e+00  1.000000e+00   
size              244.0  2.569672e+00  9.510998e-01  1.000000e+00   
price_per_person  244.0  7.888197e+00  2.914234e+00  2.880000e+00   
CC Number         244.0  2.563496e+15  2.369340e+15  6.040679e+10   

                           25%           50%           75%           max  
total_bill        1.334750e+01  1.779500e+01  2.412750e+01  5.081000e+01  
tip               2.000000e+00  2.900000e+00  3.562500e+00  1.000000e+01  
size              2.000000e+00  2.000000e+00  3.000000e+00  6.000000e+00  
price_per_person  5.800000e+00  7.255000e+00  9.390000e+00  2.027000e+01  
CC Number         3.040731e+13  3.525318e+15  4.553675e+15  6.596454e+15

In [ ]:
# Shape
df.shape

(244, 11)

In [ ]:
# This gives number of Columns
df.shape[1]

11

## Accessing the Columns in the DataFrame

In [ ]:
# Load the Data
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011812e+15    Sun4458  
3    Nathaniel Harris  4.676138e+15    Sun5260  
4        Tonya Carter  4.832733e+15    Sun2251

### Access 1 Column

In [ ]:
# Access one Column
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

### Access Multiple Columns

In [ ]:
# Access Multiple Column
df[['total_bill','tip']]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [ ]:
# Access Multiple Column
col = ['total_bill','tip']
df[col]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

### Adding a New Column to the existing DataFrame

Here we have used a **variable tip_percentage that is not existing column** if we use the **existing names the values will be toggled up.**

In [ ]:
# adding a new column
df['tip_percentage'] = 100 * df['tip']/df['total_bill']

In [ ]:
# Display
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  tip_percentage  
0  Christy Cunningham  3.560330e+15    Sun2959        5.944673  
1      Douglas Tucker  4.478070e+15    Sun4608       16.054159  
2      Travis Walters  6.011812e+15    Sun4458       16.658734  
3    Nathaniel Harris  4.676138e+15    Sun5260       13.978041  
4        Tonya Carter  4.832733e+15    Sun2251       14.680765

**round() :**This is used for rounding off the values

> **Syntax :** np.round(data , decimal = 2)



In [ ]:
# adding a new column and rounding the values to 2 decimal places
df['tip_percentage'] = np.round(100 * df['tip']/df['total_bill'],2)
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  tip_percentage  
0  Christy Cunningham  3.560330e+15    Sun2959            5.94  
1      Douglas Tucker  4.478070e+15    Sun4608           16.05  
2      Travis Walters  6.011812e+15    Sun4458           16.66  
3    Nathaniel Harris  4.676138e+15    Sun5260           13.98  
4        Tonya Carter  4.832733e+15    Sun2251           14.68

In [ ]:
# Shape
df.shape

(244, 12)

### Drop a Column from the DataFrame

**drop :** This is to delete a Column

In [ ]:
# Drop the column tip_percentage
df.drop('tip_percentage',axis = 1)

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name     CC Number Payment ID  
0    Christy Cunningham  3.560330e+15    Sun2959  
1        Douglas Tucker  4.478070e+15    Sun4608  
2        Travis Walters  6.011812e+15    Sun4458  
3      Nathaniel Harris  4.676138e+15    Sun5260  
4          Tonya Carter  4.832733e+15    Sun2251  
..                  ...           ...        ...  
239       Michael Avila  5.296069e+15    Sat2657  
240      Monica Sanders  3.506806e+15    Sat1766  
241          Keith Wong  6.011892e+15    Sat3880  
242        Dennis Dixon  4.375221e+12      Sat17  
243     Michelle Hardin  3.511452e+15    Thur672  

[244 rows x 11 columns]

Here the **Changes are not made** to make that we can use the inplace method or use the **df variabl**e for our example

In [ ]:
# Display
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  tip_percentage  
0  Christy Cunningham  3.560330e+15    Sun2959            5.94  
1      Douglas Tucker  4.478070e+15    Sun4608           16.05  
2      Travis Walters  6.011812e+15    Sun4458           16.66  
3    Nathaniel Harris  4.676138e+15    Sun5260           13.98  
4        Tonya Carter  4.832733e+15    Sun2251           14.68



*   **axis = 0 :** This **Represents Row** as Row start with(0,244) that is 243 the 244 is exclusive.
*   **axis = 1 :** This **Represents columns** as columns start with(1,11) that is 11. The 11 is inclusive.



In [ ]:
# To make the changes permenant
df = df.drop('tip_percentage',axis = 1)
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011812e+15    Sun4458  
3    Nathaniel Harris  4.676138e+15    Sun5260  
4        Tonya Carter  4.832733e+15    Sun2251

## Accessing the Rows in the DataFrame

In [ ]:
# Display the first 5 rows
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011812e+15    Sun4458  
3    Nathaniel Harris  4.676138e+15    Sun5260  
4        Tonya Carter  4.832733e+15    Sun2251

In [ ]:
# Displays the shape of the row
df.index

RangeIndex(start=0, stop=244, step=1)

### Set and Reset

**set_index() :** This is used to **set a name for the index** that has default value of 0 to 243. It gives a labeled index with a **unique column** in the table.

> **Syntax :** df.set_index('unique column name')



In [ ]:
# set the index to a unique column that is payment ID
df = df.set_index('Payment ID')
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name     CC Number  
Payment ID                                                      
Sun2959                 8.49  Christy Cunningham  3.560330e+15  
Sun4608                 3.45      Douglas Tucker  4.478070e+15  
Sun4458                 7.00      Travis Walters  6.011812e+15  
Sun5260                11.84    Nathaniel Harris  4.676138e+15  
Sun2251                 6.15        Tonya Carter  4.832733e+15

**reset_index() :** This is used to **reset a name for the index** that has labeled value of 0 to 243. It gives a default numeric index.

> **Syntax :** df.reset_index()


In [ ]:
# set the index back to default that is reset
df = df.reset_index()
df.head()

Payment ID  total_bill   tip     sex smoker  day    time  size  \
0    Sun2959       16.99  1.01  Female     No  Sun  Dinner     2   
1    Sun4608       10.34  1.66    Male     No  Sun  Dinner     3   
2    Sun4458       21.01  3.50    Male     No  Sun  Dinner     3   
3    Sun5260       23.68  3.31    Male     No  Sun  Dinner     2   
4    Sun2251       24.59  3.61  Female     No  Sun  Dinner     4   

   price_per_person          Payer Name     CC Number  
0              8.49  Christy Cunningham  3.560330e+15  
1              3.45      Douglas Tucker  4.478070e+15  
2              7.00      Travis Walters  6.011812e+15  
3             11.84    Nathaniel Harris  4.676138e+15  
4              6.15        Tonya Carter  4.832733e+15

In [ ]:
# Set the Payment ID as index
df = df.set_index('Payment ID')
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name     CC Number  
Payment ID                                                      
Sun2959                 8.49  Christy Cunningham  3.560330e+15  
Sun4608                 3.45      Douglas Tucker  4.478070e+15  
Sun4458                 7.00      Travis Walters  6.011812e+15  
Sun5260                11.84    Nathaniel Harris  4.676138e+15  
Sun2251                 6.15        Tonya Carter  4.832733e+15

### Accessing the Rows

### Accessing one Row using iloc and loc







*   **iloc :** This is for Accessing the Row using **Numeric index.**
*   **loc :** This is for Accessing the Row using **Labeled index.**



In [ ]:
# Access 1 Row
df.iloc[0]

Payment ID                     Sun2959
total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number           3560330000000000.0
Name: 0, dtype: object

In [ ]:
# Access 1 Row
df.loc['Sun2959']

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number           3560330000000000.0
Name: Sun2959, dtype: object

### Accessing Multiple Rows

In [ ]:
# Access multiple Row
df.iloc[0:4]

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   

            price_per_person          Payer Name     CC Number  
Payment ID                                                      
Sun2959                 8.49  Christy Cunningham  3.560330e+15  
Sun4608                 3.45      Douglas Tucker  4.478070e+15  
Sun4458                 7.00      Travis Walters  6.011812e+15  
Sun5260                11.84    Nathaniel Harris  4.676138e+15

In [ ]:
# Access multiple Row
df.loc[['Sun2959','Sun4608']]

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   

            price_per_person          Payer Name     CC Number  
Payment ID                                                      
Sun2959                 8.49  Christy Cunningham  3.560330e+15  
Sun4608                 3.45      Douglas Tucker  4.478070e+15

### Drop the Rows

In [ ]:
# To delete a particular row
df = df.drop('Sun2959',axis = 0)
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No  Sun  Dinner     4   

            price_per_person        Payer Name     CC Number  
Payment ID                                                    
Sun4608                 3.45    Douglas Tucker  4.478070e+15  
Sun4458                 7.00    Travis Walters  6.011812e+15  
Sun5260                11.84  Nathaniel Harris  4.676138e+15  
Sun2251                 6.15      Tonya Carter  4.832733e+15  
Sun9679                 6.32        Erik Smith  2.131404e+14

### Insert a Row

In [ ]:
# Access the first row
insert_row = df.iloc[0]
insert_row

total_bill                       10.34
tip                               1.66
sex                               Male
smoker                              No
day                                Sun
time                            Dinner
size                                 3
price_per_person                  3.45
Payer Name              Douglas Tucker
CC Number           4478070000000000.0
Name: Sun4608, dtype: object

In [ ]:
# To Insert a Row
df = df.append(insert_row)
df

<ipython-input-18-6ac78cd67504>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(insert_row)


total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   

            price_per_person        Payer Name     CC Number  
Payment ID                                                    
Sun4608                 3.45    Douglas Tucker  4.478070e+15  
Sun4458                 7.00    Travis Walters  6.011812e+15  
Sun5260                11.84  Nathaniel Harris  4.676138e+15  
Sun2251                 6.15      Tonya Carter  4.832733e+15  
Sun9679                 6.32        Erik Smith  2.131404e+14  
...                      ...               ...           ...  
Sat17                   8.91      Dennis Dixon  4.375221e+12  
Thur672                 9.39   Michelle Hardin  3.511452e+15  
Sun4608                 3.45    Douglas Tucker  4.478070e+15  
Sun4608                 3.45    Douglas Tucker  4.478070e+15  
Sun4608                 3.45    Douglas Tucker  4.478070e+15  

[246 rows x 10 columns]

### Conditional Filtering

### Single Condition



*   **Columns** are **Features**
*   **Rows** are **Instance of Data**



In [ ]:
# Read a CSV File
df = pd.read_csv('/content/drive/MyDrive/CSV/tips - tips.csv')
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011812e+15    Sun4458  
3    Nathaniel Harris  4.676138e+15    Sun5260  
4        Tonya Carter  4.832733e+15    Sun2251

In [ ]:
# Get the records with total_bill > 40
bill = df['total_bill'] > 40
bill

0      False
1      False
2      False
3      False
4      False
       ...  
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [ ]:
# Get the records with total_bill > 40
df[bill]

total_bill    tip     sex smoker   day    time  size  price_per_person  \
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07   
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04   
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77   
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03   
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94   
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27   
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78   
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08   

          Payer Name     CC Number Payment ID  
59       Brian Ortiz  6.596454e+15    Sat8139  
95     Aaron Bentley  1.800266e+14    Fri9628  
102    Heather Cohen  3.797711e+14    Sat6240  
142     Eric Andrews  4.356532e+15   Thur3621  
156    Ryan Gonzales  3.523151e+15    Sun7518  
170    Gregory Clark  5.473851e+15    Sat1954  
182     Jose Parsons  4.112210e+15    Sun2337  
184      Stephen Cox  3.547798e+15    Sun5140  
197      Brooke Soto  5.544902e+15   Thur9313  
212  Alex Williamson  6.762188e+11    Sat4590

### Multiple Condition

In [ ]:
# Get the records with total_bill > 40 and sex should be male
df[(df['total_bill'] > 40) & (df['sex'] == 'Male')]

total_bill    tip   sex smoker   day    time  size  price_per_person  \
59        48.27   6.73  Male     No   Sat  Dinner     4             12.07   
95        40.17   4.73  Male    Yes   Fri  Dinner     4             10.04   
142       41.19   5.00  Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00  Male     No   Sun  Dinner     6              8.03   
170       50.81  10.00  Male    Yes   Sat  Dinner     3             16.94   
182       45.35   3.50  Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00  Male    Yes   Sun  Dinner     2             20.27   
212       48.33   9.00  Male     No   Sat  Dinner     4             12.08   

          Payer Name     CC Number Payment ID  
59       Brian Ortiz  6.596454e+15    Sat8139  
95     Aaron Bentley  1.800266e+14    Fri9628  
142     Eric Andrews  4.356532e+15   Thur3621  
156    Ryan Gonzales  3.523151e+15    Sun7518  
170    Gregory Clark  5.473851e+15    Sat1954  
182     Jose Parsons  4.112210e+15    Sun2337  
184      Stephen Cox  3.547798e+15    Sun5140  
212  Alex Williamson  6.762188e+11    Sat4590

In [ ]:
# Get the records with total_bill > 40 or sex should be male
df[(df['total_bill'] > 40) | (df['sex'] == 'Male')]

total_bill   tip   sex smoker  day    time  size  price_per_person  \
1         10.34  1.66  Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50  Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31  Male     No  Sun  Dinner     2             11.84   
5         25.29  4.71  Male     No  Sun  Dinner     4              6.32   
6          8.77  2.00  Male     No  Sun  Dinner     2              4.38   
..          ...   ...   ...    ...  ...     ...   ...               ...   
236       12.60  1.00  Male    Yes  Sat  Dinner     2              6.30   
237       32.83  1.17  Male    Yes  Sat  Dinner     2             16.42   
239       29.03  5.92  Male     No  Sat  Dinner     3              9.68   
241       22.67  2.00  Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75  Male     No  Sat  Dinner     2              8.91   

             Payer Name     CC Number Payment ID  
1        Douglas Tucker  4.478070e+15    Sun4608  
2        Travis Walters  6.011812e+15    Sun4458  
3      Nathaniel Harris  4.676138e+15    Sun5260  
5            Erik Smith  2.131404e+14    Sun9679  
6    Kristopher Johnson  2.223728e+15    Sun5985  
..                  ...           ...        ...  
236       Matthew Myers  3.543676e+15    Sat5032  
237        Thomas Brown  4.284723e+15    Sat2929  
239       Michael Avila  5.296069e+15    Sat2657  
241          Keith Wong  6.011892e+15    Sat3880  
242        Dennis Dixon  4.375221e+12      Sat17  

[159 rows x 11 columns]

**isin() :** This is to include many Conditions and to check if it is there.

In [ ]:
# Create a option for isin()
option = ['Sat','Sun']

In [ ]:
# Check if the day is in saturday and sunday
df['day'].isin(option)

0       True
1       True
2       True
3       True
4       True
       ...  
239     True
240     True
241     True
242     True
243    False
Name: day, Length: 244, dtype: bool

In [ ]:
# Check if the day is in saturday and sunday
df[df['day'].isin(['Sat','Sun'])]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
..          ...   ...     ...    ...  ...     ...   ...               ...   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

             Payer Name     CC Number Payment ID  
0    Christy Cunningham  3.560330e+15    Sun2959  
1        Douglas Tucker  4.478070e+15    Sun4608  
2        Travis Walters  6.011812e+15    Sun4458  
3      Nathaniel Harris  4.676138e+15    Sun5260  
4          Tonya Carter  4.832733e+15    Sun2251  
..                  ...           ...        ...  
238      Kimberly Crane  6.761840e+11    Sat9777  
239       Michael Avila  5.296069e+15    Sat2657  
240      Monica Sanders  3.506806e+15    Sat1766  
241          Keith Wong  6.011892e+15    Sat3880  
242        Dennis Dixon  4.375221e+12      Sat17  

[163 rows x 11 columns]

## Apply() for Custom Functions

**Apply() :** This is used for creating custom functions.

> **Syntax :** df['new_column_name'] = df['column_name'].apply(function_name)



In [ ]:
# Read a CSV File
df = pd.read_csv('/content/drive/MyDrive/CSV/tips - tips.csv')
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011812e+15    Sun4458  
3    Nathaniel Harris  4.676138e+15    Sun5260  
4        Tonya Carter  4.832733e+15    Sun2251

In [ ]:
# fetch the Credit Card Number column
df['CC Number']

0      3.560330e+15
1      4.478070e+15
2      6.011812e+15
3      4.676138e+15
4      4.832733e+15
           ...     
239    5.296069e+15
240    3.506806e+15
241    6.011892e+15
242    4.375221e+12
243    3.511452e+15
Name: CC Number, Length: 244, dtype: float64

In [ ]:
# fetch the Credit Card Number's last four digit write a custom function
def last_four(num):
  return str(num)[-4:]

In [ ]:
# Call the function
last_four(12345678910123456789)

'6789'

In [ ]:
# To do this function on CC Number Column
df['last_four'] = df['CC Number'].apply(last_four)
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID last_four  
0  Christy Cunningham  3.560330e+15    Sun2959      00.0  
1      Douglas Tucker  4.478070e+15    Sun4608      00.0  
2      Travis Walters  6.011812e+15    Sun4458      22.0  
3    Nathaniel Harris  4.676138e+15    Sun5260      94.0  
4        Tonya Carter  4.832733e+15    Sun2251      21.0

In [ ]:
# Another Function
def bill(price):
  if(price < 10):
    return '$'
  elif(price >= 10 and price < 30):
    return '$$'
  else:
    return '$$$'

In [ ]:
# Call the function
bill(100.78)

'$$$'

In [ ]:
# Call the function
bill(10.78)

'$$'

In [ ]:
# Call the function
bill(1.78)

'$'

In [ ]:
# Now use apply()
df['bill'] = df['total_bill'].apply(bill)
df['bill']

0      $$
1      $$
2      $$
3      $$
4      $$
       ..
239    $$
240    $$
241    $$
242    $$
243    $$
Name: bill, Length: 244, dtype: object

In [ ]:
# Get the first 5 records
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID bill  
0  Christy Cunningham  3.560330e+15    Sun2959   $$  
1      Douglas Tucker  4.478070e+15    Sun4608   $$  
2      Travis Walters  6.011812e+15    Sun4458   $$  
3    Nathaniel Harris  4.676138e+15    Sun5260   $$  
4        Tonya Carter  4.832733e+15    Sun2251   $$

### Access Multiple Columns for apply()

In [ ]:
# Define a function
def quality(total_bill,tip):
  if tip/total_bill > 0.25:
    return "Generous"
  else:
    return "Other"

In [ ]:
# call the function
quality(19.76,1.01)

'Other'

In [ ]:
# Define a function to square a value
def square(num):
  return num*2

In [ ]:
# Call the function
square(2)

4

In [ ]:
# Define the same function using lambda
lambda num:num*2

<function __main__.<lambda>(num)>

In [ ]:
# Add the lambda to table columns
df['total_bill'].apply(lambda num:num*2)

0      33.98
1      20.68
2      42.02
3      47.36
4      49.18
       ...  
239    58.06
240    54.36
241    45.34
242    35.64
243    37.56
Name: total_bill, Length: 244, dtype: float64

In [ ]:
# For the columns in the tip csv file
df[['total_bill','tip']].apply(lambda df:quality(df['total_bill'],df['tip']),axis = 1)

0      Other
1      Other
2      Other
3      Other
4      Other
       ...  
239    Other
240    Other
241    Other
242    Other
243    Other
Length: 244, dtype: object

In [ ]:
# For the columns in the tip csv file
df['quality'] = df[['total_bill','tip']].apply(lambda df:quality(df['total_bill'],df['tip']),axis = 1)
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID quality  
0  Christy Cunningham  3.560330e+15    Sun2959   Other  
1      Douglas Tucker  4.478070e+15    Sun4608   Other  
2      Travis Walters  6.011812e+15    Sun4458   Other  
3    Nathaniel Harris  4.676138e+15    Sun5260   Other  
4        Tonya Carter  4.832733e+15    Sun2251   Other

### Vectorize()

**vectorize() :**This function is same as lambda this is much faster in execution.

> **Syntax :** np.vectorize(function_name)(column_names)



In [ ]:
# Using Vectorize
np.vectorize(quality)(df['total_bill'],df['tip'])

array(['Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Generous', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Generous', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Generous', 'Other', 'Other', 'Other', 'Other',
       'Oth

### Statistical Methods








In [ ]:
# Statistical Analysis
df.describe()

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

**sort_values() :** This is for arranging the values in ascending and descending order.

In [ ]:
# To sort the values according to tip
df.sort_values('tip')
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID quality  
0  Christy Cunningham  3.560330e+15    Sun2959   Other  
1      Douglas Tucker  4.478070e+15    Sun4608   Other  
2      Travis Walters  6.011812e+15    Sun4458   Other  
3    Nathaniel Harris  4.676138e+15    Sun5260   Other  
4        Tonya Carter  4.832733e+15    Sun2251   Other

In [ ]:
# To sort the values according to tip for decending order
df.sort_values('tip',ascending=False)
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID quality  
0  Christy Cunningham  3.560330e+15    Sun2959   Other  
1      Douglas Tucker  4.478070e+15    Sun4608   Other  
2      Travis Walters  6.011812e+15    Sun4458   Other  
3    Nathaniel Harris  4.676138e+15    Sun5260   Other  
4        Tonya Carter  4.832733e+15    Sun2251   Other

In [ ]:
# To sort the values according to tip
df.sort_values(['tip','size'])
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID quality  
0  Christy Cunningham  3.560330e+15    Sun2959   Other  
1      Douglas Tucker  4.478070e+15    Sun4608   Other  
2      Travis Walters  6.011812e+15    Sun4458   Other  
3    Nathaniel Harris  4.676138e+15    Sun5260   Other  
4        Tonya Carter  4.832733e+15    Sun2251   Other



*   **max() :** To find maximum value.
*   **min() :** To find minimum value.



In [ ]:
# To find the maximum value
df['total_bill'].max()

50.81



*   **idxmax() :** Gives the Index of Maximum record.
*   **idxmin() :** Gives the Index of Minimum record.



In [ ]:
# To find the maximum value's index
df['total_bill'].idxmax()

170

In [ ]:
# the info of that 170th row
df.iloc[df['total_bill'].idxmax()]

total_bill                       50.81
tip                               10.0
sex                               Male
smoker                             Yes
day                                Sat
time                            Dinner
size                                 3
price_per_person                 16.94
Payer Name               Gregory Clark
CC Number           5473850968388236.0
Payment ID                     Sat1954
quality                          Other
Name: 170, dtype: object

**Corr() :**The corr() method calculates the **relationship** between each column in your data set.


>**The number varies from -1 to 1.**

*   **1 means** that there is a 1 to 1 relationship (a **perfect correlation**).
*   **0.9 is also a good relationship**, and if you **increase one value**, the **other will probably increase** as well.

*   **-0.9 would be just as good relationship as 0.9**, but if you **increase one value**, the **other will probably go down.**
*   **0.2 means NOT a good relationship**, meaning that if one value goes up does not mean that the other will.

In [ ]:
# To find the relationship between columns
df.corr()

<ipython-input-5-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

**value_counts() :**Counts the Number of categorical values in a column.

In [ ]:
# Count the number of males and females
df['sex'].value_counts()

Male      157
Female     87
Name: sex, dtype: int64

**unique() :** This to to display the names of unique categorical value.

In [ ]:
# To find the unique categorical values name
df['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

**nunique() :** This to to display the number of unique categorical value.

In [ ]:
# To find the unique number of categorical values
df['day'].nunique()

4

**replace() :**It is to replace a value by something else.

In [ ]:
# Replace females and males to F and M
df['sex'].replace(['Female','Male'],['F','M'])

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

**map() :** Similar to that of replace but it is faster than replace. this maps the given value to that value.

In [ ]:
# Create a map dictionary
mymap = {'Female':'F','Male':'M'}

In [ ]:
# Same Function can be done with map()
df['sex'].map(mymap)

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

In [ ]:
#  create a dataframe
simple = pd.DataFrame([1,2,2,3,3,4],['a','b','c','d','e','f'])
simple

0
a  1
b  2
c  2
d  3
e  3
f  4

**duplicated() :**This gives true when a duplicate value is found.

In [ ]:
# Find Duplicates
simple.duplicated()

a    False
b    False
c     True
d    False
e     True
f    False
dtype: bool

**drop_duplicates() :**This drops the true boolean value that is a duplicate value.

In [ ]:
# To drop the duplicated values
simple.drop_duplicates()

0
a  1
b  2
d  3
f  4

**between() :**This is to get the values between a given range and it gets if that value is inclusive or not.

In [ ]:
# Between()
df['total_bill'].between(10,20,inclusive = True)

<ipython-input-19-9877f2a4adbb>:2: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  df['total_bill'].between(10,20,inclusive = True)


0       True
1       True
2      False
3      False
4      False
       ...  
239    False
240    False
241    False
242     True
243     True
Name: total_bill, Length: 244, dtype: bool

In [ ]:
# Between()
df[df['total_bill'].between(10,20,inclusive = True)]

<ipython-input-20-ea694117a2d5>:2: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  df[df['total_bill'].between(10,20,inclusive = True)]


total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
8         15.04  1.96    Male     No   Sun  Dinner     2              7.52   
9         14.78  3.23    Male     No   Sun  Dinner     2              7.39   
10        10.27  1.71    Male     No   Sun  Dinner     2              5.14   
..          ...   ...     ...    ...   ...     ...   ...               ...   
234       15.53  3.00    Male    Yes   Sat  Dinner     2              7.76   
235       10.07  1.25    Male     No   Sat  Dinner     2              5.04   
236       12.60  1.00    Male    Yes   Sat  Dinner     2              6.30   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name     CC Number Payment ID  
0    Christy Cunningham  3.560330e+15    Sun2959  
1        Douglas Tucker  4.478070e+15    Sun4608  
8       Joseph Mcdonald  3.522866e+15    Sun6820  
9         Jerome Abbott  3.532125e+15    Sun3775  
10        William Riley  5.662876e+11    Sun2546  
..                  ...           ...        ...  
234       Tracy Douglas  4.097940e+15    Sat7220  
235       Sean Gonzalez  3.534021e+15    Sat4615  
236       Matthew Myers  3.543676e+15    Sat5032  
242        Dennis Dixon  4.375221e+12      Sat17  
243     Michelle Hardin  3.511452e+15    Thur672  

[130 rows x 11 columns]

**nlargest() :** This will get the largest record with the given column to compare.

In [ ]:
# Give the first 5 largest tip record
df.nlargest(5,'tip')

total_bill    tip   sex smoker   day    time  size  price_per_person  \
170       50.81  10.00  Male    Yes   Sat  Dinner     3             16.94   
212       48.33   9.00  Male     No   Sat  Dinner     4             12.08   
23        39.42   7.58  Male     No   Sat  Dinner     4              9.86   
59        48.27   6.73  Male     No   Sat  Dinner     4             12.07   
141       34.30   6.70  Male     No  Thur   Lunch     6              5.72   

          Payer Name     CC Number Payment ID  
170    Gregory Clark  5.473851e+15    Sat1954  
212  Alex Williamson  6.762188e+11    Sat4590  
23    Lance Peterson  3.542584e+15     Sat239  
59       Brian Ortiz  6.596454e+15    Sat8139  
141   Steven Carlson  3.526516e+15   Thur1025

**nsmallest() :** This will get the smallest record with the given column to compare.

In [ ]:
# Give the first 5 smallest tip record
df.nsmallest(2,'tip')

total_bill  tip     sex smoker  day    time  size  price_per_person  \
67        3.07  1.0  Female    Yes  Sat  Dinner     1              3.07   
92        5.75  1.0  Female    Yes  Fri  Dinner     2              2.88   

       Payer Name     CC Number Payment ID  
67  Tiffany Brock  4.359489e+15    Sat3455  
92   Leah Ramirez  3.508912e+15    Fri3780

In [ ]:
# nlargest and nsmallest are fastest than sort yet both are same
df.sort_values('tip',ascending=True).iloc[0:2]

total_bill  tip     sex smoker  day    time  size  price_per_person  \
67         3.07  1.0  Female    Yes  Sat  Dinner     1              3.07   
236       12.60  1.0    Male    Yes  Sat  Dinner     2              6.30   

        Payer Name     CC Number Payment ID  
67   Tiffany Brock  4.359489e+15    Sat3455  
236  Matthew Myers  3.543676e+15    Sat5032

**sample() :** This gives random records from the dataset.

In [ ]:
# Using Sample() get any 5 records from the dataset
df.sample(5)

total_bill   tip     sex smoker   day    time  size  price_per_person  \
85       34.83  5.17  Female     No  Thur   Lunch     4              8.71   
27       12.69  2.00    Male     No   Sat  Dinner     2              6.34   
10       10.27  1.71    Male     No   Sun  Dinner     2              5.14   
7        26.88  3.12    Male     No   Sun  Dinner     4              6.72   
41       17.46  2.54    Male     No   Sun  Dinner     2              8.73   

        Payer Name     CC Number Payment ID  
85     Shawna Cook  6.011790e+15   Thur7972  
27  Patrick Barber  3.015555e+13     Sat394  
10   William Riley  5.662876e+11    Sun2546  
7      Robert Buck  3.514785e+15    Sun8157  
41     David Boyer  3.536678e+15    Sun9460

## Missing Data

Missing Data can be handled by:

*   **Keeping** the Missing Data
*   **Removing** the Missing Data

*   **Replacing** the Missing Data






### Methods in Missing Values

In [ ]:
# Load the Dataset with Missing Values
df = pd.read_csv('/content/drive/MyDrive/CSV/movie_scores - movie_scores.csv')
df

first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
# Check if nan is equal to nan
np.nan

nan

In [ ]:
# Check if nan is equal to nan
pd.NaT

NaT

In [ ]:
# Check
np.nan == np.nan

False

In [ ]:
# Check
np.nan is np.nan

True

In [ ]:
# Check
myvar = np.nan
myvar is np.nan

True

In [ ]:
# Check for any missing values in the dataset
df.isnull()

first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [ ]:
# Check for any missing values in the dataset
df.notnull()

first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [ ]:
# Get the Column pre_movie_score with missing values
df['pre_movie_score'].isnull()

0    False
1     True
2     True
3    False
4    False
Name: pre_movie_score, dtype: bool

In [ ]:
# Get the Column pre_movie_score with missing values
df[df['pre_movie_score'].isnull()]

first_name last_name   age  sex  pre_movie_score  post_movie_score
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN

In [ ]:
# Get pre_movie_score with missing values and first name with value
df[(df['pre_movie_score'].isnull() & df['first_name'].notnull())]

first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

### Keep the Missing Value

In [ ]:
# Keeping the Missing Values
df

first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

### Drop / Remove the Missing Value

**dropna() :** This Drops the **whole row** with **NaN** Value.

In [ ]:
# Removing the Missing Value
df.dropna()

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

**dropna(thresh = 4) :**This is used to **include** the value with **records available upto 4 threshold.**

In [ ]:
# Removing the Missing Value
df.dropna(thresh = 4)

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

Here the **Thresh = 5** the **record 2** is **excluded.**

In [ ]:
# Removing the Missing Value
df.dropna(thresh = 5)

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

**dropna(axis = 1) :** This will **remove** all columns with **even one NaN**.

In [ ]:
# Removing the Missing Value
df.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
# Removing the Missing Value
df.dropna(axis = 0)

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

**dropna(subset = ['column_name']) :** This will fetch the value or add the value with atleast the last_name in our dataset.

In [ ]:
# Removing the Missing Value
df.dropna(subset = ['last_name'])

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

### Replace / Fill the Missing Value

**fillna() :** This is used to fill the missing values.

In [ ]:
# Fill the Missing Values using the word NULL
df.fillna('NULL')

first_name last_name   age   sex pre_movie_score post_movie_score
0        Tom     Hanks  63.0     m             8.0             10.0
1       NULL      NULL  NULL  NULL            NULL             NULL
2       Hugh   Jackman  51.0     m            NULL             NULL
3      Oprah   Winfrey  66.0     f             6.0              8.0
4       Emma     Stone  31.0     f             7.0              9.0

In [ ]:
# Fill the Missing Values in pre_movie_score with 0
df['pre_movie_score'].fillna(0)

0    8.0
1    0.0
2    0.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

Here we fill the **Missing values** with **mean().**

In [ ]:
# Fill the Missing Values in pre_movie_score with its mean() value
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

0    8.0
1    7.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [ ]:
# Fill the Missing Values with its mean() value
df.fillna(df.mean())

<ipython-input-29-61a1d332a313>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean())


first_name last_name    age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.00    m              8.0              10.0
1        NaN       NaN  52.75  NaN              7.0               9.0
2       Hugh   Jackman  51.00    m              7.0               9.0
3      Oprah   Winfrey  66.00    f              6.0               8.0
4       Emma     Stone  31.00    f              7.0               9.0

**interpolate() :** This function takes the **upper and lower bound of the current NaN value** to find that **NaN value at an approx.**

In [ ]:
# create a series
dict = {'members':7.0,'group_no':np.nan,'salary':1000,'bonus':500}

In [ ]:
# Create a Series
ser = pd.Series(dict)
ser

members        7.0
group_no       NaN
salary      1000.0
bonus        500.0
dtype: float64

In [ ]:
# To find an Approx value to group_no use interpolate()
ser.interpolate()

members        7.0
group_no     503.5
salary      1000.0
bonus        500.0
dtype: float64

## Groupby()

In [ ]:
# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/CSV/mpg - mpg.csv')
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model_year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [ ]:
# using value_counts()
df['model_year'].value_counts()

73    40
78    36
76    34
82    31
75    30
70    29
79    29
80    29
81    29
71    28
72    28
77    28
74    27
Name: model_year, dtype: int64

**groupby() :**This groupby() is used to group **categorical values** and sometimes **numerical values in categorical pattern** and displays the values.It is called the **lazy function** in pandas as it **doesn't work without an aggregate function.**

> **Syntax :** df.groupby().Aggreate_functions()



In [ ]:
# Using groupby()
df.groupby('model_year')

### Using Single Value

In [ ]:
# Using groupby() with aggregate function
df.groupby('model_year').value_counts()

model_year  mpg   cylinders  displacement  horsepower  weight  acceleration  origin  name              
70          9.0   8          304.0         193         4732    18.5          1       hi 1200d              1
            10.0  8          307.0         200         4376    15.0          1       chevy c20             1
            25.0  4          104.0         95          2375    17.5          2       saab 99e              1
            24.0  4          107.0         90          2430    14.5          2       audi 100 ls           1
            22.0  6          198.0         95          2833    15.5          1       plymouth duster       1
                                                                                                          ..
82          31.0  4          91.0          68          1970    17.6          3       mazda glc custom      1
            29.0  4          135.0         84          2525    16.0          1       dodge aries se        1
            28.0  4     

In [ ]:
# Using groupby() with aggregate function
df.groupby('model_year').mean()

<ipython-input-14-35d424ba34dd>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('model_year').mean()


mpg  cylinders  displacement       weight  acceleration  \
model_year                                                                  
70          17.689655   6.758621    281.413793  3372.793103     12.948276   
71          21.250000   5.571429    209.750000  2995.428571     15.142857   
72          18.714286   5.821429    218.375000  3237.714286     15.125000   
73          17.100000   6.375000    256.875000  3419.025000     14.312500   
74          22.703704   5.259259    171.740741  2877.925926     16.203704   
75          20.266667   5.600000    205.533333  3176.800000     16.050000   
76          21.573529   5.647059    197.794118  3078.735294     15.941176   
77          23.375000   5.464286    191.392857  2997.357143     15.435714   
78          24.061111   5.361111    177.805556  2861.805556     15.805556   
79          25.093103   5.827586    206.689655  3055.344828     15.813793   
80          33.696552   4.137931    115.827586  2436.655172     16.934483   
81          30.334483   4.620690    135.310345  2522.931034     16.306897   
82          31.709677   4.193548    128.870968  2453.548387     16.638710   

              origin  
model_year            
70          1.310345  
71          1.428571  
72          1.535714  
73          1.375000  
74          1.666667  
75          1.466667  
76          1.470588  
77          1.571429  
78          1.611111  
79          1.275862  
80          2.206897  
81          1.965517  
82          1.645161

### Using Multiple Values

In [ ]:
# Using groupby() with aggregate function with Multiple values
df.groupby(['model_year','cylinders']).mean()

<ipython-input-15-9026a031c737>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['model_year','cylinders']).mean()


mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         4          25.285714    107.000000  2292.571429     16.000000   
           6          20.500000    199.000000  2710.500000     15.500000   
           8          14.111111    367.555556  3940.055556     11.194444   
71         4          27.461538    101.846154  2056.384615     16.961538   
           6          18.000000    243.375000  3171.875000     14.750000   
           8          13.428571    371.714286  4537.714286     12.214286   
72         3          19.000000     70.000000  2330.000000     13.500000   
           4          23.428571    111.535714  2382.642857     17.214286   
           8          13.615385    344.846154  4228.384615     13.000000   
73         3          18.000000     70.000000  2124.000000     13.500000   
           4          22.727273    109.272727  2338.090909     17.136364   
           6          19.000000    212.250000  2917.125000     15.687500   
           8          13.200000    365.250000  4279.050000     12.250000   
74         4          27.800000     96.533333  2151.466667     16.400000   
           6          17.857143    230.428571  3320.000000     16.857143   
           8          14.200000    315.200000  4438.400000     14.700000   
75         4          25.250000    114.833333  2489.250000     15.833333   
           6          17.583333    233.750000  3398.333333     17.708333   
           8          15.666667    330.500000  4108.833333     13.166667   
76         4          26.766667    106.333333  2306.600000     16.866667   
           6          20.000000    221.400000  3349.600000     17.000000   
           8          14.666667    324.000000  4064.666667     13.222222   
77         3          21.500000     80.000000  2720.000000     13.500000   
           4          29.107143    106.500000  2205.071429     16.064286   
           6          19.500000    220.400000  3383.000000     16.900000   
           8          16.000000    335.750000  4177.500000     13.662500   
78         4          29.576471    112.117647  2296.764706     16.282353   
           5          20.300000    131.000000  2830.000000     15.900000   
           6          19.066667    213.250000  3314.166667     16.391667   
           8          19.050000    300.833333  3563.333333     13.266667   
79         4          31.525000    113.583333  2357.583333     15.991667   
           5          25.400000    183.000000  3530.000000     20.100000   
           6          22.950000    205.666667  3025.833333     15.433333   
           8          18.630000    321.400000  3862.900000     15.400000   
80         3          23.700000     70.000000  2420.000000     12.500000   
           4          34.612000    111.000000  2360.080000     17.144000   
           5          36.400000    121.000000  2950.000000     19.900000   
           6          25.900000    196.500000  3145.500000     15.050000   
81         4          32.814286    108.857143  2275.476190     16.466667   
           6          23.428571    184.000000  3093.571429     15.442857   
           8          26.600000    350.000000  3725.000000     19.000000   
82         4          32.071429    118.571429  2402.321429     16.703571   
           6          28.333333    225.000000  2931.666667     16.033333   

                        origin  
model_year cylinders            
70         4          2.285714  
           6          1.000000  
           8          1.000000  
71         4          1.923077  
           6          1.000000  
           8          1.000000  
72         3          3.000000  
           4          1.928571  
           8          1.000000  
73         3          3.000000  
           4          2.000000  
           6          1.250000  
           8          1.000000  
74         4          2.200000  
           6          1.000000  
           8          1.000000  
75         4 

In [ ]:
# Using groupby() with describe()
df.groupby(['model_year','cylinders']).describe()

mpg                                                    \
                     count       mean       std   min     25%    50%     75%   
model_year cylinders                                                           
70         4           7.0  25.285714  1.112697  24.0  24.500  25.00  26.000   
           6           4.0  20.500000  1.732051  18.0  20.250  21.00  21.250   
           8          18.0  14.111111  2.609685   9.0  14.000  14.50  15.000   
71         4          13.0  27.461538  3.502746  22.0  25.000  27.00  30.000   
           6           8.0  18.000000  1.069045  16.0  17.750  18.00  19.000   
           8           7.0  13.428571  0.786796  12.0  13.000  14.00  14.000   
72         3           1.0  19.000000       NaN  19.0  19.000  19.00  19.000   
           4          14.0  23.428571  3.056249  18.0  21.250  23.00  25.750   
           8          13.0  13.615385  1.502135  11.0  13.000  13.00  14.000   
73         3           1.0  18.000000       NaN  18.0  18.000  18.00  18.000   
           4          11.0  22.727273  3.319365  19.0  20.000  22.00  25.000   
           6           8.0  19.000000  2.203893  16.0  18.000  18.00  20.250   
           8          20.0  13.200000  1.361114  11.0  12.000  13.00  14.000   
74         4          15.0  27.800000  2.932576  24.0  26.000  26.00  31.000   
           6           7.0  17.857143  2.267787  15.0  16.000  18.00  19.500   
           8           5.0  14.200000  1.095445  13.0  14.000  14.00  14.000   
75         4          12.0  25.250000  3.333712  22.0  23.000  24.00  26.000   
           6          12.0  17.583333  2.020726  15.0  15.750  18.00  19.000   
           8           6.0  15.666667  2.422120  13.0  14.250  15.50  16.000   
76         4          15.0  26.766667  3.825976  19.0  25.000  27.00  29.000   
           6          10.0  20.000000  2.494438  16.5  18.125  19.50  22.000   
           8           9.0  14.666667  1.767767  13.0  13.000  14.50  16.000   
77         3           1.0  21.500000       NaN  21.5  21.500  21.50  21.500   
           4          14.0  29.107143  4.039129  21.5  25.625  30.00  31.250   
           6           5.0  19.500000  1.767767  17.5  18.500  19.00  20.500   
           8           8.0  16.000000  0.845154  15.0  15.500  15.75  16.250   
78         4          17.0  29.576471  6.384799  21.1  23.900  29.50  32.800   
           5           1.0  20.300000       NaN  20.3  20.300  20.30  20.300   
           6          12.0  19.066667  1.548802  16.2  18.000  19.30  20.500   
           8           6.0  19.050000  1.048332  17.5  18.375  19.30  19.775   
79         4          12.0  31.525000  4.349739  22.3  28.150  32.70  34.275   
           5           1.0  25.400000       NaN  25.4  25.400  25.40  25.400   
           6           6.0  22.950000  3.851104  19.8  20.300  21.05  25.475   
           8          10.0  18.630000  2.757636  15.5  16.925  17.90  19.025   
80         3           1.0  23.700000       NaN  23.7  23.700  23.70  23.700   
           4          25.0  34.612000  6.597621  23.6  29.800  33.80  40.800   
           5           1.0  36.400000       NaN  36.4  36.400  36.40  36.400   
           6           2.0  25.900000  9.616652  19.1  22.500  25.90  29.300   
81         4          21.0  32.814286  3.844904  25.8  30.000  33.00  34.700   
           6           7.0  23.428571  4.139531  17.6  21.300  23.50  24.800   
           8           1.0  26.600000       NaN  26.6  26.600  26.60  26.600   
82         4          28.0  32.071429  5.054727  23.0  27.750  32.00  36.000   
           6           3.0  28.333333  8.504901  22.0  23.500  25.00  31.500   

                           displacement              ... acceleration        \
                       max        count        mean  ...          75%   max   
model_year cylinders                                 ...                      
70         4          27.0          7.0  107.000000  ...       17.500  20.5   
           6          22.0

In [ ]:
# Using groupby() with describe() and transpose()
df.groupby(['model_year','cylinders']).describe().transpose()

model_year                   70                                     71  \
cylinders                     4            6            8            4   
mpg          count     7.000000     4.000000    18.000000    13.000000   
             mean     25.285714    20.500000    14.111111    27.461538   
             std       1.112697     1.732051     2.609685     3.502746   
             min      24.000000    18.000000     9.000000    22.000000   
             25%      24.500000    20.250000    14.000000    25.000000   
             50%      25.000000    21.000000    14.500000    27.000000   
             75%      26.000000    21.250000    15.000000    30.000000   
             max      27.000000    22.000000    18.000000    35.000000   
displacement count     7.000000     4.000000    18.000000    13.000000   
             mean    107.000000   199.000000   367.555556   101.846154   
             std       8.660254     0.816497    59.076443    23.053728   
             min      97.000000   198.000000   302.000000    71.000000   
             25%     100.500000   198.750000   309.750000    88.000000   
             50%     107.000000   199.000000   355.000000    97.000000   
             75%     111.500000   199.250000   421.750000   116.000000   
             max     121.000000   200.000000   455.000000   140.000000   
weight       count     7.000000     4.000000    18.000000    13.000000   
             mean   2292.571429  2710.500000  3940.055556  2056.384615   
             std     263.055037   112.837641   496.964488   217.933300   
             min    1835.000000  2587.000000  3086.000000  1613.000000   
             25%    2182.000000  2632.750000  3518.750000  1955.000000   
             50%    2372.000000  2711.000000  3805.500000  2074.000000   
             75%    2402.500000  2788.750000  4370.500000  2220.000000   
             max    2672.000000  2833.000000  4732.000000  2408.000000   
acceleration count     7.000000     4.000000    18.000000    13.000000   
             mean     16.000000    15.500000    11.194444    16.961538   
             std       2.661453     0.408248     2.668657     2.536907   
             min      12.500000    15.000000     8.000000    14.000000   
             25%      14.500000    15.375000     9.625000    14.500000   
             50%      15.000000    15.500000    10.250000    18.000000   
             75%      17.500000    15.625000    12.000000    19.000000   
             max      20.500000    16.000000    18.500000    20.500000   
origin       count     7.000000     4.000000    18.000000    13.000000   
             mean      2.285714     1.000000     1.000000     1.923077   
             std       0.487950     0.000000     0.000000     0.862316   
             min       2.000000     1.000000     1.000000     1.000000   
             25%       2.000000     1.000000     1.000000     1.000000   
             50%       2.000000     1.000000     1.000000     2.000000   
             75%       2.500000     1.000000     1.000000     3.000000   
             max       3.000000     1.000000     1.000000     3.000000   

model_year                                        72               \
cylinders                     6            8       3            4   
mpg          count     8.000000     7.000000     1.0    14.000000   
             mean     18.000000    13.428571    19.0    23.428571   
             std       1.069045     0.786796     NaN     3.056249   
             min      16.000000    12.000000    19.0    18.000000   
             25%      17.750000    13.000000    19.0    21.250000   
             50%      18.000000    14.000000    19.0    23.000000   
             75%      19.000000    14.000000    19.0    25.750000   
             max      19.000000    14.000000    19.0    28.000000   
displacement count     8.000000     7.000000     1.0    14.000000   
             mean    243.375000   371.714286    70.0   111.535714   
             std      11.867573    32.438220     NaN    14.1672

**index :**This will get the values of (col_1,col_2)

In [ ]:
# Using groupby() with mean() and find the index
df.groupby(['model_year','cylinders']).mean().index

<ipython-input-19-41964e684dcf>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['model_year','cylinders']).mean().index


MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

**columns :**This will get the column names.

In [ ]:
# Using groupby() with mean() and columns names
df.groupby(['model_year','cylinders']).mean().columns

<ipython-input-20-dc7c363c46b2>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['model_year','cylinders']).mean().columns


Index(['mpg', 'displacement', 'weight', 'acceleration', 'origin'], dtype='object')

Here,the model_year and cylinders are not columns but labels

In [ ]:
# Using groupby()
df.groupby(['model_year','cylinders']).mean()['mpg']

<ipython-input-21-769e02e710ca>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['model_year','cylinders']).mean()['mpg']


model_year  cylinders
70          4            25.285714
            6            20.500000
            8            14.111111
71          4            27.461538
            6            18.000000
            8            13.428571
72          3            19.000000
            4            23.428571
            8            13.615385
73          3            18.000000
            4            22.727273
            6            19.000000
            8            13.200000
74          4            27.800000
            6            17.857143
            8            14.200000
75          4            25.250000
            6            17.583333
            8            15.666667
76          4            26.766667
            6            20.000000
            8            14.666667
77          3            21.500000
            4            29.107143
            6            19.500000
            8            16.000000
78          4            29.576471
            5            20.30000

In [ ]:
# Using groupby()
year_cyl = df.groupby(['model_year','cylinders']).mean()
year_cyl

<ipython-input-24-cbf8f69e1992>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  year_cyl = df.groupby(['model_year','cylinders']).mean()


mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         4          25.285714    107.000000  2292.571429     16.000000   
           6          20.500000    199.000000  2710.500000     15.500000   
           8          14.111111    367.555556  3940.055556     11.194444   
71         4          27.461538    101.846154  2056.384615     16.961538   
           6          18.000000    243.375000  3171.875000     14.750000   
           8          13.428571    371.714286  4537.714286     12.214286   
72         3          19.000000     70.000000  2330.000000     13.500000   
           4          23.428571    111.535714  2382.642857     17.214286   
           8          13.615385    344.846154  4228.384615     13.000000   
73         3          18.000000     70.000000  2124.000000     13.500000   
           4          22.727273    109.272727  2338.090909     17.136364   
           6          19.000000    212.250000  2917.125000     15.687500   
           8          13.200000    365.250000  4279.050000     12.250000   
74         4          27.800000     96.533333  2151.466667     16.400000   
           6          17.857143    230.428571  3320.000000     16.857143   
           8          14.200000    315.200000  4438.400000     14.700000   
75         4          25.250000    114.833333  2489.250000     15.833333   
           6          17.583333    233.750000  3398.333333     17.708333   
           8          15.666667    330.500000  4108.833333     13.166667   
76         4          26.766667    106.333333  2306.600000     16.866667   
           6          20.000000    221.400000  3349.600000     17.000000   
           8          14.666667    324.000000  4064.666667     13.222222   
77         3          21.500000     80.000000  2720.000000     13.500000   
           4          29.107143    106.500000  2205.071429     16.064286   
           6          19.500000    220.400000  3383.000000     16.900000   
           8          16.000000    335.750000  4177.500000     13.662500   
78         4          29.576471    112.117647  2296.764706     16.282353   
           5          20.300000    131.000000  2830.000000     15.900000   
           6          19.066667    213.250000  3314.166667     16.391667   
           8          19.050000    300.833333  3563.333333     13.266667   
79         4          31.525000    113.583333  2357.583333     15.991667   
           5          25.400000    183.000000  3530.000000     20.100000   
           6          22.950000    205.666667  3025.833333     15.433333   
           8          18.630000    321.400000  3862.900000     15.400000   
80         3          23.700000     70.000000  2420.000000     12.500000   
           4          34.612000    111.000000  2360.080000     17.144000   
           5          36.400000    121.000000  2950.000000     19.900000   
           6          25.900000    196.500000  3145.500000     15.050000   
81         4          32.814286    108.857143  2275.476190     16.466667   
           6          23.428571    184.000000  3093.571429     15.442857   
           8          26.600000    350.000000  3725.000000     19.000000   
82         4          32.071429    118.571429  2402.321429     16.703571   
           6          28.333333    225.000000  2931.666667     16.033333   

                        origin  
model_year cylinders            
70         4          2.285714  
           6          1.000000  
           8          1.000000  
71         4          1.923077  
           6          1.000000  
           8          1.000000  
72         3          3.000000  
           4          1.928571  
           8          1.000000  
73         3          3.000000  
           4          2.000000  
           6          1.250000  
           8          1.000000  
74         4          2.200000  
           6          1.000000  
           8          1.000000  
75         4 

**names :** This fetches the index labels alone.

In [ ]:
# getting the index names
year_cyl.index.names

FrozenList(['model_year', 'cylinders'])

**levels :** This fetches the model_yeara and the cylinders unique values

In [ ]:
# getting the index levels
year_cyl.index.levels

FrozenList([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], [3, 4, 5, 6, 8]])

In [ ]:
# getting the records of some rows through Broadcast selection
year_cyl.loc[70:72]

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         4          25.285714    107.000000  2292.571429     16.000000   
           6          20.500000    199.000000  2710.500000     15.500000   
           8          14.111111    367.555556  3940.055556     11.194444   
71         4          27.461538    101.846154  2056.384615     16.961538   
           6          18.000000    243.375000  3171.875000     14.750000   
           8          13.428571    371.714286  4537.714286     12.214286   
72         3          19.000000     70.000000  2330.000000     13.500000   
           4          23.428571    111.535714  2382.642857     17.214286   
           8          13.615385    344.846154  4228.384615     13.000000   

                        origin  
model_year cylinders            
70         4          2.285714  
           6          1.000000  
           8          1.000000  
71         4          1.923077  
           6          1.000000  
           8          1.000000  
72         3          3.000000  
           4          1.928571  
           8          1.000000

In [ ]:
# getting the records of some rows
year_cyl.loc[[70,82]]

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         4          25.285714    107.000000  2292.571429     16.000000   
           6          20.500000    199.000000  2710.500000     15.500000   
           8          14.111111    367.555556  3940.055556     11.194444   
82         4          32.071429    118.571429  2402.321429     16.703571   
           6          28.333333    225.000000  2931.666667     16.033333   

                        origin  
model_year cylinders            
70         4          2.285714  
           6          1.000000  
           8          1.000000  
82         4          1.714286  
           6          1.000000

In [ ]:
# getting the records of few required rows
year_cyl.loc[(70,8)]

mpg               14.111111
displacement     367.555556
weight          3940.055556
acceleration      11.194444
origin             1.000000
Name: (70, 8), dtype: float64

### groupby for Multi-level Index

**cross-section :** This is used for getting or fetching values much in a **easier** way than loc[] used for accessing values.The **key can take only one value.**

In [ ]:
# Use Cross-section
year_cyl.xs(key=70,level='model_year')

mpg  displacement       weight  acceleration    origin
cylinders                                                              
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [ ]:
# Using Cross-section fetch the cylinders with key value 4
year_cyl.xs(key=4,level='cylinders')

mpg  displacement       weight  acceleration    origin
model_year                                                              
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

In [ ]:
# Using Cross-section fetch the cylinders with key value 4
year_cyl.xs(key=4,level='cylinders').loc[70:72]

mpg  displacement       weight  acceleration    origin
model_year                                                              
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571

In [ ]:
# Using Cross-section fetch the cylinders with key value 4
year_cyl.xs(key=4,level='cylinders')['mpg']

model_year
70    25.285714
71    27.461538
72    23.428571
73    22.727273
74    27.800000
75    25.250000
76    26.766667
77    29.107143
78    29.576471
79    31.525000
80    34.612000
81    32.814286
82    32.071429
Name: mpg, dtype: float64

In [ ]:
# To fetch only values 3,6,8 from all the model_years
df[df['cylinders'].isin([3,6,8])].groupby(['model_year','cylinders']).mean()

<ipython-input-46-d61ce819efe2>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df[df['cylinders'].isin([3,6,8])].groupby(['model_year','cylinders']).mean()


mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         6          20.500000    199.000000  2710.500000     15.500000   
           8          14.111111    367.555556  3940.055556     11.194444   
71         6          18.000000    243.375000  3171.875000     14.750000   
           8          13.428571    371.714286  4537.714286     12.214286   
72         3          19.000000     70.000000  2330.000000     13.500000   
           8          13.615385    344.846154  4228.384615     13.000000   
73         3          18.000000     70.000000  2124.000000     13.500000   
           6          19.000000    212.250000  2917.125000     15.687500   
           8          13.200000    365.250000  4279.050000     12.250000   
74         6          17.857143    230.428571  3320.000000     16.857143   
           8          14.200000    315.200000  4438.400000     14.700000   
75         6          17.583333    233.750000  3398.333333     17.708333   
           8          15.666667    330.500000  4108.833333     13.166667   
76         6          20.000000    221.400000  3349.600000     17.000000   
           8          14.666667    324.000000  4064.666667     13.222222   
77         3          21.500000     80.000000  2720.000000     13.500000   
           6          19.500000    220.400000  3383.000000     16.900000   
           8          16.000000    335.750000  4177.500000     13.662500   
78         6          19.066667    213.250000  3314.166667     16.391667   
           8          19.050000    300.833333  3563.333333     13.266667   
79         6          22.950000    205.666667  3025.833333     15.433333   
           8          18.630000    321.400000  3862.900000     15.400000   
80         3          23.700000     70.000000  2420.000000     12.500000   
           6          25.900000    196.500000  3145.500000     15.050000   
81         6          23.428571    184.000000  3093.571429     15.442857   
           8          26.600000    350.000000  3725.000000     19.000000   
82         6          28.333333    225.000000  2931.666667     16.033333   

                        origin  
model_year cylinders            
70         6          1.000000  
           8          1.000000  
71         6          1.000000  
           8          1.000000  
72         3          3.000000  
           8          1.000000  
73         3          3.000000  
           6          1.250000  
           8          1.000000  
74         6          1.000000  
           8          1.000000  
75         6          1.000000  
           8          1.000000  
76         6          1.300000  
           8          1.000000  
77         3          3.000000  
           6          1.400000  
           8          1.000000  
78         6          1.166667  
           8          1.000000  
79         6          1.000000  
           8          1.000000  
80         3          3.000000  
           6          2.000000  
81         6          1.714286  
           8          1.000000  
82         6          1.000000

In [ ]:
# sorting the multilevel index
year_cyl.sort_index(level='model_year',ascending=False)

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
82         6          28.333333    225.000000  2931.666667     16.033333   
           4          32.071429    118.571429  2402.321429     16.703571   
81         8          26.600000    350.000000  3725.000000     19.000000   
           6          23.428571    184.000000  3093.571429     15.442857   
           4          32.814286    108.857143  2275.476190     16.466667   
80         6          25.900000    196.500000  3145.500000     15.050000   
           5          36.400000    121.000000  2950.000000     19.900000   
           4          34.612000    111.000000  2360.080000     17.144000   
           3          23.700000     70.000000  2420.000000     12.500000   
79         8          18.630000    321.400000  3862.900000     15.400000   
           6          22.950000    205.666667  3025.833333     15.433333   
           5          25.400000    183.000000  3530.000000     20.100000   
           4          31.525000    113.583333  2357.583333     15.991667   
78         8          19.050000    300.833333  3563.333333     13.266667   
           6          19.066667    213.250000  3314.166667     16.391667   
           5          20.300000    131.000000  2830.000000     15.900000   
           4          29.576471    112.117647  2296.764706     16.282353   
77         8          16.000000    335.750000  4177.500000     13.662500   
           6          19.500000    220.400000  3383.000000     16.900000   
           4          29.107143    106.500000  2205.071429     16.064286   
           3          21.500000     80.000000  2720.000000     13.500000   
76         8          14.666667    324.000000  4064.666667     13.222222   
           6          20.000000    221.400000  3349.600000     17.000000   
           4          26.766667    106.333333  2306.600000     16.866667   
75         8          15.666667    330.500000  4108.833333     13.166667   
           6          17.583333    233.750000  3398.333333     17.708333   
           4          25.250000    114.833333  2489.250000     15.833333   
74         8          14.200000    315.200000  4438.400000     14.700000   
           6          17.857143    230.428571  3320.000000     16.857143   
           4          27.800000     96.533333  2151.466667     16.400000   
73         8          13.200000    365.250000  4279.050000     12.250000   
           6          19.000000    212.250000  2917.125000     15.687500   
           4          22.727273    109.272727  2338.090909     17.136364   
           3          18.000000     70.000000  2124.000000     13.500000   
72         8          13.615385    344.846154  4228.384615     13.000000   
           4          23.428571    111.535714  2382.642857     17.214286   
           3          19.000000     70.000000  2330.000000     13.500000   
71         8          13.428571    371.714286  4537.714286     12.214286   
           6          18.000000    243.375000  3171.875000     14.750000   
           4          27.461538    101.846154  2056.384615     16.961538   
70         8          14.111111    367.555556  3940.055556     11.194444   
           6          20.500000    199.000000  2710.500000     15.500000   
           4          25.285714    107.000000  2292.571429     16.000000   

                        origin  
model_year cylinders            
82         6          1.000000  
           4          1.714286  
81         8          1.000000  
           6          1.714286  
           4          2.095238  
80         6          2.000000  
           5          2.000000  
           4          2.200000  
           3          3.000000  
79         8          1.000000  
           6          1.000000  
           5          2.000000  
           4          1.583333  
78         8          1.000000  
           6          1.166667  
           5          2.000000  
           4 

### Advance way of using many Aggregate functions

**agg() :**This is used for multiple aggregate functions.

In [ ]:
# Using many aggregate functions
year_cyl.agg(['std','mean'])

mpg  displacement       weight  acceleration    origin
std    6.143211     98.464268   738.135196      2.009202  0.646951
mean  22.418920    196.629156  3058.263088     15.530132  1.622542

In [ ]:
# Using many aggregate functions for a particular column
year_cyl.agg(['std','mean'])['mpg']

std      6.143211
mean    22.418920
Name: mpg, dtype: float64

In [ ]:
# Using dictionary
df.agg({'mpg':['max','std'],'weight':['max','min','sum']})

mpg     weight
max  46.600000     5140.0
std   7.815984        NaN
min        NaN     1613.0
sum        NaN  1182229.0

In [ ]:
# Using dictionary fill the null values with 'NULL'
df.agg({'mpg':['max','std'],'weight':['max','min','sum']}).fillna('NULL')

mpg     weight
max      46.6     5140.0
std  7.815984       NULL
min      NULL     1613.0
sum      NULL  1182229.0

## Combining Rows and Columns in a table

In [ ]:
# Create 2 dictionaries
dict_1 = {'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']}
dict_2 = {'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']}

In [ ]:
# Create DataFrames
one = pd.DataFrame(dict_1)
two = pd.DataFrame(dict_2)

In [ ]:
# Print the DataFrame one
one

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [ ]:
# Print the DataFrame two
two

C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [ ]:
# Combine the 2 DataFrames by column
pd.concat([one,two],axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
# Combine the 2 DataFrames by rows
pd.concat([one,two],axis=0)

A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

In [ ]:
# rename the column C and D to A and B
two.columns

Index(['C', 'D'], dtype='object')

In [ ]:
# rename the column C and D to A and B
two.columns = one.columns

In [ ]:
# Print two
two

A   B
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [ ]:
# Combine the 2 DataFrames by rows
combine_row = pd.concat([one,two],axis=0)
combine_row

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [ ]:
# get the indices
combine_row.index

Int64Index([0, 1, 2, 3, 0, 1, 2, 3], dtype='int64')

In [ ]:
# get the indices
combine_row.index = range(len(combine_row))
combine_row

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  C0  D0
5  C1  D1
6  C2  D2
7  C3  D3

## Merge

### Inner Merge

**inner merge :** Inner Merge **find common between the DataFrames** and gets the result.

In [ ]:
# Create 2 dataframes
registrations = pd.DataFrame({'Reg_id':[1,2,3,4],'name':['Jungkook','Jimin','Taehyung','Jhope']})
logins = pd.DataFrame({'login_id':[1,2,3,4],'name':['Namjoon','Taehyung','Jungkook','SeokJin']})

In [ ]:
# Print the DataFrame
registrations

Reg_id      name
0       1  Jungkook
1       2     Jimin
2       3  Taehyung
3       4     Jhope

In [ ]:
# Print the DataFrame
logins

login_id      name
0         1   Namjoon
1         2  Taehyung
2         3  Jungkook
3         4   SeokJin

**merge() :**This is to combine the dataframes.

> **Syntax :**pd.merge(dataframe_1,dataframe_2,how='inner',on = which column)



In [ ]:
# combine using Merge()
pd.merge(registrations,logins,how='inner',on='name')

Reg_id      name  login_id
0       1  Jungkook         3
1       3  Taehyung         2

### Left and Right Merge



*   **Left Merge:**Prints all the **left table values.**
*   **Right Merge:**Prints all the **Right table values.**



In [ ]:
# Left Merge
pd.merge(left=registrations,right=logins,how='left',on='name')

Reg_id      name  login_id
0       1  Jungkook       3.0
1       2     Jimin       NaN
2       3  Taehyung       2.0
3       4     Jhope       NaN

In [ ]:
# Right Merge
pd.merge(left=registrations,right=logins,how='right',on='name')

Reg_id      name  login_id
0     NaN   Namjoon         1
1     3.0  Taehyung         2
2     1.0  Jungkook         3
3     NaN   SeokJin         4

### Outer Merge

**outer merge :** This displays **all the values** in all the DataFrames.

In [ ]:
# Outer Merge
pd.merge(registrations,logins,how='outer',on='name')

Reg_id      name  login_id
0     1.0  Jungkook       3.0
1     2.0     Jimin       NaN
2     3.0  Taehyung       2.0
3     4.0     Jhope       NaN
4     NaN   Namjoon       1.0
5     NaN   SeokJin       4.0

In [ ]:
# Merge Using Index
registrations.set_index('name')

Reg_id
name            
Jungkook       1
Jimin          2
Taehyung       3
Jhope          4

In [ ]:
# Print logins
logins

login_id      name
0         1   Namjoon
1         2  Taehyung
2         3  Jungkook
3         4   SeokJin

In [ ]:
#pd.merge(registrations,logins,left_index=True,right_on='name',how='inner')

In [ ]:
# reset index
registrations.reset_index()

index  Reg_id      name
0      0       1  Jungkook
1      1       2     Jimin
2      2       3  Taehyung
3      3       4     Jhope

In [ ]:
# Replace names of columns
registrations.columns = ['reg_id','reg_name']
registration

reg_id  reg_name
0       1  Jungkook
1       2     Jimin
2       3  Taehyung
3       4     Jhope

In [ ]:
# Merge using different column name not using common names
pd.merge(registrations,logins,left_on='reg_name',right_on='name',how='inner')

reg_id  reg_name  login_id      name
0       1  Jungkook         3  Jungkook
1       3  Taehyung         2  Taehyung

In [ ]:
# Replace the column names
registrations.columns = ['id','name']
logins.columns = ['id','name']

In [ ]:
# print DataFrames
registrations

id      name
0   1  Jungkook
1   2     Jimin
2   3  Taehyung
3   4     Jhope

In [ ]:
# print DataFrames
logins

id      name
0   1   Namjoon
1   2  Taehyung
2   3  Jungkook
3   4   SeokJin

In [ ]:
# Merge using same column names for both DataFrames
pd.merge(registrations,logins,how='inner',on='name')

id_x      name  id_y
0     1  Jungkook     3
1     3  Taehyung     2

In [ ]:
# Merge using inner with suffixes()
pd.merge(registrations,logins,how='inner',on='name',suffixes = ('_reg','_log'))

id_reg      name  id_log
0       1  Jungkook       3
1       3  Taehyung       2

## String Methods

In [ ]:
# Create an Email
email = 'jungkook@gmail.com'

**split() :**This is used to split a string.

In [ ]:
# Split the email
email.split('@')

['jungkook', 'gmail.com']

In [ ]:
# create a series
name = pd.Series(['Jungkook','Taehyung','Namjoon','Jimin','5'])
name

0    Jungkook
1    Taehyung
2     Namjoon
3       Jimin
4           5
dtype: object

In [ ]:
# Use the string method upper()
name.str.upper()

0    JUNGKOOK
1    TAEHYUNG
2     NAMJOON
3       JIMIN
4           5
dtype: object

In [ ]:
# Use the string method isalnum()
name.str.isalnum()

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [ ]:
# Use the string method isdigit()
name.str.isdigit()

0    False
1    False
2    False
3    False
4     True
dtype: bool

Here we combine few names together that is **Vocalists  and Rappers all together in the group BTS.**

In [ ]:
# Create a Series
bts = pd.Series(['Jungkook,Taehyung,Jimin,Jin','Namjoon,Yoongi,Jhope'])
bts

0    Jungkook,Taehyung,Jimin,Jin
1           Namjoon,Yoongi,Jhope
dtype: object

In [ ]:
# Split the Series
bts.str.split(',')

0    [Jungkook, Taehyung, Jimin, Jin]
1            [Namjoon, Yoongi, Jhope]
dtype: object

In [ ]:
# Split the Series get the vocals line in BTS Group
bts.str.split(',')[0]

['Jungkook', 'Taehyung', 'Jimin', 'Jin']

In [ ]:
# Split the Series get the vocals line in BTS Group
vocals_line = 'Jungkook,Taehyung,Jimin,Jin'
vocals_line

'Jungkook,Taehyung,Jimin,Jin'

In [ ]:
# Split the Series get the vocals line in BTS Group
vocals_line.split(',')

['Jungkook', 'Taehyung', 'Jimin', 'Jin']

In [ ]:
# Split the Series get the vocals line in BTS Group
vocals_line.split(',')[0]

'Jungkook'

In [ ]:
# Create a series
BTS  = pd.Series(bts)
BTS

0    Jungkook,Taehyung,Jimin,Jin
1           Namjoon,Yoongi,Jhope
dtype: object

**expand :**This will **expand a series to a dataframe.**

In [ ]:
# Expand the series
BTS.str.split(',',expand=True)

0         1      2     3
0  Jungkook  Taehyung  Jimin   Jin
1   Namjoon    Yoongi  Jhope  None

### Cleaning the Data

In [ ]:
# create a series
maknaes = pd.Series(['  jungkook  ','tae;hyung','jimin  '])
maknaes

0      jungkook  
1       tae;hyung
2         jimin  
dtype: object

In [ ]:
# Cleaning the data
maknaes.str.replace(';','')

0      jungkook  
1        taehyung
2         jimin  
dtype: object

**strip() :**This is to **remove whitespaces** in a string.

In [ ]:
# Cleaning the data
maknaes.str.replace(';','').str.strip()

0    jungkook
1    taehyung
2       jimin
dtype: object

**capitalize() :**This is used to make the **start of a string to uppercase.**

In [ ]:
# Clensed Data
maknaes.str.replace(';','').str.strip().str.capitalize()

0    Jungkook
1    Taehyung
2       Jimin
dtype: object

Here we use **custom function** that is **more efficient** for **complex functions.**

In [ ]:
# Cleaning data using custom function
def clean(name):
  name = name.replace(';','')
  name = name.strip()
  name = name.capitalize()
  return name

In [ ]:
# This is done using apply()
maknaes.apply(clean)

0    Jungkook
1    Taehyung
2       Jimin
dtype: object

## DateTime



> **Syntax :** to_datetime(year,month,day,hours,minutes,seconds)



In [ ]:
# Load DateTime Library
from datetime import datetime

In [ ]:
# create a series
myser = pd.Series(['Nov 16,1997','1997-09-01',None])
myser

0    Nov 16,1997
1     1997-09-01
2           None
dtype: object

**dayfirst :** This converts the **Year-Day-Month to Year-Month-Day.**

In [ ]:
# create a datetime
#timer = pd.to_datetime(myser)
#pd.to_datetime(myser,dayfirst=True)

## Data Input and Output

### CSV File


In [ ]:
# Read a csv file
df = pd.read_csv('/content/drive/MyDrive/CSV/example - example.csv')
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [ ]:
# Read a csv file
df = pd.read_csv('/content/drive/MyDrive/CSV/example - example.csv',index_col=0)
df

b   c   d
a             
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15

In [ ]:
# Read a csv file
df = pd.read_csv('/content/drive/MyDrive/CSV/example - example.csv',header=None)
df

0   1   2   3
0   a   b   c   d
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15

In [ ]:
# writing the dataset to an empty csv file
df.to_csv('/content/drive/MyDrive/CSV/newfile - Sheet1 (1).csv')
df

0   1   2   3
0   a   b   c   d
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15

### HTML File

In [ ]:
# Read a HTML file
url=('https://en.wikipedia.org/wiki/World_population')

In [ ]:
# read a html file
tables = pd.read_html(url)
len(tables)

29

In [ ]:
# Access the elements
tables[0]

Population         1     2     3     4     5     6     7     8     9  \
0           Year      1804  1927  1960  1974  1987  1999  2011  2022  2037   
1  Years elapsed  200,000+   123    33    14    13    12    12    11    15   

     10  
0  2057  
1    20

In [ ]:
# Access the elements
tables[2]

0                                                  1
0 NaN  Graphs are unavailable due to technical issues...

In [ ]:
# Access the elements
tables[7]

Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][103]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520
5     6                 Lebanon     5296814       10400                509
6     7                  Rwanda    13173730       26338                500
7     8                 Burundi    12696478       27830                456
8     9                   India  1389637446     3287263                423
9    10             Netherlands    17400824       41543                419

In [ ]:
# Access the elements
tables[4]

Rank Country / Dependency  Population  Percentage of the world  \
0     1                India  1425775850                      NaN   
1     2                China  1412600000                      NaN   
2     3        United States   335831092                      NaN   
3     4            Indonesia   278696200                      NaN   
4     5             Pakistan   229488994                      NaN   
5     6              Nigeria   216746934                      NaN   
6     7               Brazil   217017905                      NaN   
7     8           Bangladesh   168220000                      NaN   
8     9               Russia   147190000                      NaN   
9    10               Mexico   128271248                      NaN   

          Date Source (official or from the United Nations)  
0  14 Apr 2023                            UN projection[92]  
1  31 Dec 2021                 National annual estimate[93]  
2  12 Dec 2023                National population clock[94]  
3   1 Jul 2023                 National annual estimate[95]  
4   1 Jul 2022                            UN projection[96]  
5   1 Jul 2022                            UN projection[96]  
6  12 Dec 2023                National population clock[97]  
7   1 Jul 2020               Annual Population Estimate[98]  
8   1 Oct 2021          2021 preliminary census results[99]  
9  31 Mar 2022                                          NaN

In [ ]:
# Access the elements with the column names
tables[5].columns

MultiIndex([(                                                                                                       '#', ...),
            (                                                                                 'Most populous countries', ...),
            (                                                                                                    '2000', ...),
            (                                                                                                    '2015', ...),
            (                                                                                                 '2030[A]', ...),
            ('Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.', ...)],
           )

In [ ]:
# Access the elements and store in a variable
world = tables[5]
world

#  \
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
   Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.   
0                                                 NaN                                                         
1                                                   1                                                         
2                                                   2                                                         
3                                                   3                                                         
4                                                   4                                                         
5                                                   5                                                         
6                                                   6                                                         
7                                                   7                                                         
8                                                   8                                                         
9                                                   9                                                         
10                                                 10                                                         
11                                                NaN                                                         
12  Notes: .mw-parser-output .reflist{font-size:90...                                                         

                              Most populous countries  \
                                   Unnamed: 1_level_1   
                                   Unnamed: 1_level_2   
                                   Unnamed: 1_level_3   
                                   Unnamed: 1_level_4   
                                   Unnamed: 1_level_5   
                                   Unnamed: 1_level_6   
                                   Unnamed: 1_level_7   
                                   Unnamed: 1_level_8   
                                   Unnamed: 1_level_9   
                                  Unnamed: 1_level_10   
                                  Unnamed: 1_level_11   
0   Graphs are unavailable due to technical issues...   
1                                            China[B]   
2                                               India   
3                                       United States   
4                                           Indonesia   
5                                            Pakistan   
6                                              Brazil   
7                                             Nigeria   
8                                          Bangladesh   
9                                              Russia   
10                                             Mexico   
11                 

In [ ]:
# Process the table
world = world.drop('#',axis=1)

<ipython-input-6-4a5cdbfc4c04>:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  world = world.drop('#',axis=1)


In [ ]:
# Process the table
world = world.drop('Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.',axis=1)

<ipython-input-7-cdfd0dfdbdec>:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  world = world.drop('Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.',axis=1)


In [ ]:
# Process the table
world.columns = ['Top Ten Countries','2000','2015','2030']
world

Top Ten Countries  \
0   Graphs are unavailable due to technical issues...   
1                                            China[B]   
2                                               India   
3                                       United States   
4                                           Indonesia   
5                                            Pakistan   
6                                              Brazil   
7                                             Nigeria   
8                                          Bangladesh   
9                                              Russia   
10                                             Mexico   
11                                        World total   
12  Notes: .mw-parser-output .reflist{font-size:90...   

                                                 2000  \
0                                                 NaN   
1                                                1270   
2                                                1053   
3                                                 283   
4                                                 212   
5                                                 136   
6                                                 176   
7                                                 123   
8                                                 131   
9                                                 146   
10                                                103   
11                                               6127   
12  Notes: .mw-parser-output .reflist{font-size:90...   

                                                 2015  \
0                                                 NaN   
1                                                1376   
2                                                1311   
3                                                 322   
4                                                 258   
5                                                 208   
6                                                 206   
7                                                 182   
8                                                 161   
9                                                 146   
10                                                127   
11                                               7349   
12  Notes: .mw-parser-output .reflist{font-size:90...   

                                                 2030  
0                                                 NaN  
1                                                1416  
2                                                1528  
3                                                 356  
4                                                 295  
5                                                 245  
6                                                 228  
7                                                 263  
8                                                 186  
9                                                 149  
10                                                148  
11                                               8501  
12  Notes: .mw-parser-output .reflist{font-size:90...

In [ ]:
# Process the table
world = world.set_index('Top Ten Countries')
world

2000  \
Top Ten Countries                                                                                       
Graphs are unavailable due to technical issues....                                                NaN   
China[B]                                                                                         1270   
India                                                                                            1053   
United States                                                                                     283   
Indonesia                                                                                         212   
Pakistan                                                                                          136   
Brazil                                                                                            176   
Nigeria                                                                                           123   
Bangladesh                                                                                        131   
Russia                                                                                            146   
Mexico                                                                                            103   
World total                                                                                      6127   
Notes: .mw-parser-output .reflist{font-size:90%...  Notes: .mw-parser-output .reflist{font-size:90...   

                                                                                                 2015  \
Top Ten Countries                                                                                       
Graphs are unavailable due to technical issues....                                                NaN   
China[B]                                                                                         1376   
India                                                                                            1311   
United States                                                                                     322   
Indonesia                                                                                         258   
Pakistan                                                                                          208   
Brazil                                                                                            206   
Nigeria                                                                                           182   
Bangladesh                                                                                        161   
Russia                                                                                            146   
Mexico                                                                                            127   
World total                                                                                      7349   
Notes: .mw-parser-output .reflist{font-size:90%...  Notes: .mw-parser-output .reflist{font-size:90...   

                                                                                                 2030  
Top Ten Countries                                                                                      
Graphs are unavailable due to technical issues....                                                NaN  
China[B]                                                                                         1416  
India                                                                                            1528  
United States                                                                                     356  
Indonesia                                                                                         295  
Pakistan                                                                                          245  
Brazil                                                                                            228  
Nigeria  

In [ ]:
# Process the table
world = world.drop('Graphs are unavailable due to technical issues. There is more info on Phabricator and on MediaWiki wiki.',axis=0)

In [ ]:
# Process the table
world

2000  \
Top Ten Countries                                                                                       
China[B]                                                                                         1270   
India                                                                                            1053   
United States                                                                                     283   
Indonesia                                                                                         212   
Pakistan                                                                                          136   
Brazil                                                                                            176   
Nigeria                                                                                           123   
Bangladesh                                                                                        131   
Russia                                                                                            146   
Mexico                                                                                            103   
World total                                                                                      6127   
Notes: .mw-parser-output .reflist{font-size:90%...  Notes: .mw-parser-output .reflist{font-size:90...   

                                                                                                 2015  \
Top Ten Countries                                                                                       
China[B]                                                                                         1376   
India                                                                                            1311   
United States                                                                                     322   
Indonesia                                                                                         258   
Pakistan                                                                                          208   
Brazil                                                                                            206   
Nigeria                                                                                           182   
Bangladesh                                                                                        161   
Russia                                                                                            146   
Mexico                                                                                            127   
World total                                                                                      7349   
Notes: .mw-parser-output .reflist{font-size:90%...  Notes: .mw-parser-output .reflist{font-size:90...   

                                                                                                 2030  
Top Ten Countries                                                                                      
China[B]                                                                                         1416  
India                                                                                            1528  
United States                                                                                     356  
Indonesia                                                                                         295  
Pakistan                                                                                          245  
Brazil                                                                                            228  
Nigeria                                                                                           263  
Bangladesh                                                                                        186  
Russia                                                                                            149  
Mexico     

In [ ]:
# Process the table
world = world.drop('Notes: .mw-parser-output .reflist{font-size:90%;margin-bottom:0.5em;list-style-type:decimal}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman} ^ 2030 = Medium variant. ^ China excludes Hong Kong and Macau.',axis=0)

In [ ]:
# Process the table
world

2000  2015  2030
Top Ten Countries                  
China[B]           1270  1376  1416
India              1053  1311  1528
United States       283   322   356
Indonesia           212   258   295
Pakistan            136   208   245
Brazil              176   206   228
Nigeria             123   182   263
Bangladesh          131   161   186
Russia              146   146   149
Mexico              103   127   148
World total        6127  7349  8501

In [ ]:
# Process the table
world = world.rename({'China[B]':'China'})
world

2000  2015  2030
Top Ten Countries                  
China              1270  1376  1416
India              1053  1311  1528
United States       283   322   356
Indonesia           212   258   295
Pakistan            136   208   245
Brazil              176   206   228
Nigeria             123   182   263
Bangladesh          131   161   186
Russia              146   146   149
Mexico              103   127   148
World total        6127  7349  8501

In [ ]:
# store the values in a new file - writing
world.to_html('newfile.html')

### Excel File

In [ ]:
# read the excel sheet
df = pd.read_excel('/content/drive/MyDrive/CSV/example.xlsx',sheet_name='First_Sheet')
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [ ]:
# Create a work book
wb = pd.ExcelFile('/content/drive/MyDrive/CSV/example.xlsx')
wb

In [ ]:
# Get the sheet name that is the key
wb.sheet_names

['First_Sheet']

In [ ]:
# read excel file with no sheet name
excel_file_dict = pd.read_excel('/content/drive/MyDrive/CSV/example.xlsx',sheet_name=None)
excel_file_dict

{'First_Sheet':     a   b   c   d
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15}

In [ ]:
# Find the type
type(excel_file_dict)

dict

In [ ]:
# Getting the keys
excel_file_dict.keys()

dict_keys(['First_Sheet'])

In [ ]:
# Get the dataset
my_excel = excel_file_dict['First_Sheet']
my_excel

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [ ]:
# Write into another excel file
my_excel.to_excel('newfile1.xlsx',sheet_name='Fisrt_sheet',index=False)

### SQL

In [ ]:
# Load the Library
from sqlalchemy import create_engine

In [ ]:
# Creating temporary database
temp_db = create_engine('sqlite:///:memory:')

In [ ]:
# Create a DataFrame
df = pd.DataFrame(np.random.randint(0,100,(4,4)),columns = ['a','b','c','d'])
df

a   b   c   d
0  84  59  21  46
1  21  83  49  38
2  28  81  67  42
3  68  89  64  78

In [ ]:
# Create a database table
df.to_sql(name='new_table_1',con=temp_db)

4

In [ ]:
# new_df = pd.read_sql(sql='new_table',con=temp_db)
# new_df

In [ ]:
# result = pd.read_sql_query(sql="SELECT a,c FROM new_table",con=temp_db)
# result